### ISSUE TITLE
Protected master branch?

### ISSUE THREAD

**Issue by owickstrom** [owickstrom/pandoc-include-code#28]
What do you say we protect the master branch on Github and use PRs and reviews? I want to add more collaborators (starting with @srid, @barskern, @normenmueller) so that the maintenance and development of this project won't get stuck when I'm unavailable. Using a PR workflow requiring 1 accepted review by a collaborator sounds like a decent start to me.

**Comment by barskern** [comment]
I agree.

**Comment by aubertc** [comment]
Does somebody else have write access to the repo, in the end?

A [straightforward pull request](https://github.com/owickstrom/pandoc-include-code/pull/32) was emitted, but it is still pending review by an approved member…

**Comment by owickstrom** [comment]
This has fallen the cracks. I've added @srid, @barskern, and @normenmueller as collaborators. I've not yet switched to a protected branch, but I'll do that now.

If anyone has time to review the PR that would be greatly appreciated! I'll take a look myself now.
