### ISSUE TITLE
Migrate to pandoc 2.10

### ISSUE THREAD

**Issue by aubertc** [owickstrom/pandoc-include-code#30]
Pandoc just released its [2.10 version](https://github.com/jgm/pandoc/releases/tag/2.10), but unfortunately the current version of pandoc-include-code is not compatible with it:

```
pandoc 2.10
Compiled with pandoc-types 1.21, texmath 0.12.0.2, skylighting 0.8.5
```

pandoc-include-code installed with `cabal install pandoc-include-code` (so, version 1.5.0.0),
```
cabal info pandoc-include-code
* pandoc-include-code (program and library)
    Synopsis:      A Pandoc filter for including code from source files
    Versions available: 0.1.0, 0.2.0, 0.3.0, 1.1.1.0, 1.2.0.1, 1.2.0.2, 1.3.0.0,
                        1.4.0.0, 1.5.0.0 (and 3 others)
    Versions installed: 1.5.0.0
```

For a dummy `test_pandoc-include-code.md` file, I get

```
$ pandoc --filter pandoc-include-code -o test_pandoc-include-code.pdf test_pandoc-include-code.md
pandoc-include-code: Error in $: Incompatible API versions: encoded with [1,21] but attempted to decode with [1,20].
CallStack (from HasCallStack):
  error, called at ./Text/Pandoc/JSON.hs:112:48 in pandoc-types-1.20-LV3cWb5FIUUL5HoopYvbQN:Text.Pandoc.JSON
Error running filter pandoc-include-code:
Filter returned error status 1
```

**Comment by aubertc** [comment]
A possible work-around:

- Download [pandoc-types 1.21](https://hackage.haskell.org/package/pandoc-types-1.21/pandoc-types-1.21.tar.gz), extract and install it using `cabal configure` and then `cabal install`
- Download the original source code of pandoc-include-code
- Edit pandoc-include-code.cabal by replacing every ` 1.20` with ` 1.21`, bump the version to 1.5.0.1,
- Install pandoc-include-cabal with `cabal configure` and then `cabal install`

**Comment by iandol** [comment]
Am I right in inferring this error appear to be part of the reason (alongside pandoc-citeproc) macOS package manager homebrew cannot update its Pandoc package (https://github.com/Homebrew/homebrew-core/pull/57476), even for those us us who don't use your filter?

**Comment by chenrui333** [comment]
@iandol @aubertc FYI, I have incorporated the patch and ship out pandoc 2.10 in the homebrew-core side.
