### ISSUE TITLE
Add `.travis.yml` to build releases for users without Haskell environment on their machine?

### ISSUE THREAD

**Issue by doronbehar** [owickstrom/pandoc-include-code#4]
Hello, this filter looks wonderful and it would be very nice to package it and distribute it for users without Haskell development environment on their machine like in the Arch Linux community just like [`pandoc-citeproc-bin`](https://aur.archlinux.org/packages/pandoc-citeproc-bin) and [`pandoc-crossref-bin`](https://aur.archlinux.org/packages/pandoc-crossref-bin) which do not rely on any Haskell dependencies in comparison to their 'official' versions: [`pandoc-citeproc`](https://www.archlinux.org/packages/community/x86_64/pandoc-citeproc/) and [`pandoc-crossref`](https://www.archlinux.org/packages/community/x86_64/pandoc-crossref/). See this discussion for more info:
https://www.reddit.com/r/haskell/comments/6jj8ha/whats_going_on_in_archlinux_pandoc_requires_1gb/

What I'm trying to say is that it would be great if you could add a `.travis.yml` so that everybody would be able to use the compiled executable of this pandoc filter from the [`releases`](https://github.com/owickstrom/pandoc-include-code/releases) page of this repository here on GitHub, perhaps similarly to @lierdakil [`pandoc-crossref`](https://github.com/lierdakil/pandoc-crossref)'s [`.travis.yml`](https://github.com/lierdakil/pandoc-crossref/blob/master/.travis.yml).

The package [`pandoc-crossref-bin`](https://aur.archlinux.org/packages/pandoc-crossref-bin) is a great example for users' usage of Travis' builds - read [line 15 of `pandoc-crossref-bin`'s `PKGBUILD`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pandoc-crossref-bin#n15&id=f7b7ab401fd7eaead45fa9d06f570da79016d8bb).

What do you think?

**Comment by owickstrom** [comment]
Hi! Thank you for you kind words, and for this detailed proposal. I'm up for making binaries available in the GitHub releases page, but I can't take any responsibility for the Arch Linux side of things. Also, I'm a bit short on time, so I'm not sure when I can make this happen. But as you've added links to similar projects, it shouldn't be too much work.

Sounds ok? :)

**Comment by doronbehar** [comment]
I won't mind trying, but I have no experience at all with building anything with `cabal` or using the [Haskell Platform](http://hackage.haskell.org/platform/). I don't even have a Haskell environment on my machine (Those dependencies weight a lot..).
How different could be this project's `.travis.yml` from `pandoc-crossref`'s? You both use the Haskell Platform pretty much the same, at least according to your `README`s...

**Comment by lierdakil** [comment]
You could probably just copy-paste my `.travis.yml` and only tweak the deployment part, in particular `api_key`, obviously, and executable name.

That said, those binaries aren't actually statically-linked. They don't have much in terms of library dependencies, and tend to work "out of the box" on modern Linux distributions, but YMMV. I was a bit too lazy to fumble around with static linking (it's non-trivial, especially on an external CI)

**Comment by owickstrom** [comment]
@doronbehar OK, I finally got around to setting this up. :smile: Tagged releases are now built and published to GitHub Releases as discussed.

**Comment by doronbehar** [comment]
Thanks!
I added it to the AUR without as well: https://aur.archlinux.org/packages/pandoc-include-code-bin/
